---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: confluence-local-home
  labels:
    app: confluence
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
