---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitbucket-local-home
  labels:
    app: bitbucket
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitbucket-shared-home
  labels:
    app: bitbucket
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

