apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 60s
    openshift.io/host.generated: "true"
  labels:
    app.kubernetes.io/instance: jira
    app.kubernetes.io/name: jira
  name: jira
  namespace: atlassian
spec:
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: jira
    weight: 100
  wildcardPolicy: None
