---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atlassian-shared-home
  labels:
    app: bitbucket
    app: jira
    app: confluence
    app: crowd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: efs-sc

